### ISSUE TITLE
r_c's "object" variable name in templates conflicts with Rails 2.3 nested forms

### ISSUE THREAD

**Issue by jensb** [jamesgolick/resource_controller#4]
Hi,

I use r_c 0.6.5 with Rails 2.3. According to the nested forms documentation, "object" within a nested fields_for block, when using nested forms, refers to the current child object. However, r_c seems to override this variable name globally for the complete template:

Whenever in my template, I do things like

```
<% form_for(@parent) do |form| %>
...
  <% form.fields_for :children do |child| %>
    <%= object.name %> is <%= object.age %> years old.
    <%= child.check_box :candy %> Allow more candy? <br/>
  <% end %>
...
<% end %>
```

I get an error 

```
undefined method `name' for #<Parent:0x39fff44>
```

For me, this looks like r_c is overwriting the "object" variable since it obviously refers to the parent and not the current child within the block.

Can "object" within r_c be renamed or replaced easily? If anything just to debug this problem?
Thanks!

Jens

**Comment by jamesgolick** [comment]
r_c doesn't overwrite the object variable, it creates a method called object that gets exposed as a helper. It looks to me like your problem here is that you should be receiving a parameter to your block called object, but you're not. Otherwise, where would the object reference come from?

**Comment by jensb** [comment]
You're right, I should have written "child.object.age" above, not "object.age". Sorry!
